In [2]:
import pandas as pd

df = pd.read_csv("../datasets/aac_intakes_outcomes.csv")

In [3]:
df.head(5)

,age_upon_outcome,animal_id_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,...,age_upon_intake_age_group,intake_datetime,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days
0,10 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,...,"(7.5, 10.0]",2017-12-07 00:00:00,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194
1,7 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,...,"(5.0, 7.5]",2014-12-19 10:21:00,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722
2,6 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,...,"(5.0, 7.5]",2014-03-07 14:26:00,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889
3,10 years,A047759,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,...,"(7.5, 10.0]",2014-04-02 15:55:00,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139
4,16 years,A134067,1997-10-16 00:00:00,NaN,Return to Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,...,"(15.0, 17.5]",2013-11-16 09:02:00,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444

In [4]:
df["outcome_type"].unique()

<StringArray>
['Return to Owner',        'Transfer',        'Adoption',      'Euthanasia',
            'Died',       'Rto-Adopt',         'Missing',        'Disposal',
               nan,        'Relocate']
Length: 10, dtype: str

In [5]:
#Remove duplicate intake and outcome columns
df = df.drop(columns=["outcome_subtype", "age_upon_outcome_(years)", "age_upon_outcome_age_group", "outcome_month", "outcome_year", "outcome_monthyear", "outcome_weekday", "outcome_hour", "outcome_number", "dob_monthyear", "count", "age_upon_intake_(years)", "age_upon_intake_age_group", "intake_month", "intake_year", "intake_monthyear", "intake_weekday", "intake_hour", "time_in_shelter_days" ])

df.head(5)

,age_upon_outcome,animal_id_outcome,date_of_birth,outcome_type,sex_upon_outcome,age_upon_outcome_(days),outcome_datetime,dob_year,dob_month,age_upon_intake,...,breed,color,found_location,intake_condition,intake_type,sex_upon_intake,age_upon_intake_(days),intake_datetime,intake_number,time_in_shelter
0,10 years,A006100,2007-07-09 00:00:00,Return to Owner,Neutered Male,3650,2017-12-07 14:07:00,2007,7,10 years,...,Spinone Italiano Mix,Yellow/White,Colony Creek And Hunters Trace in Austin (TX),Normal,Stray,Neutered Male,3650,2017-12-07 00:00:00,1.0,0 days 14:07:00.000000000
1,7 years,A006100,2007-07-09 00:00:00,Return to Owner,Neutered Male,2555,2014-12-20 16:35:00,2007,7,7 years,...,Spinone Italiano Mix,Yellow/White,8700 Research Blvd in Austin (TX),Normal,Public Assist,Neutered Male,2555,2014-12-19 10:21:00,2.0,1 days 06:14:00.000000000
2,6 years,A006100,2007-07-09 00:00:00,Return to Owner,Neutered Male,2190,2014-03-08 17:10:00,2007,7,6 years,...,Spinone Italiano Mix,Yellow/White,8700 Research in Austin (TX),Normal,Public Assist,Neutered Male,2190,2014-03-07 14:26:00,3.0,1 days 02:44:00.000000000
3,10 years,A047759,2004-04-02 00:00:00,Transfer,Neutered Male,3650,2014-04-07 15:12:00,2004,4,10 years,...,Dachshund,Tricolor,Austin (TX),Normal,Owner Surrender,Neutered Male,3650,2014-04-02 15:55:00,1.0,4 days 23:17:00.000000000
4,16 years,A134067,1997-10-16 00:00:00,Return to Owner,Neutered Male,5840,2013-11-16 11:54:00,1997,10,16 years,...,Shetland Sheepdog,Brown/White,12034 Research Blvd in Austin (TX),Injured,Public Assist,Neutered Male,5840,2013-11-16 09:02:00,1.0,0 days 02:52:00.000000000